### PR TITLE
Reenable cl

### PR DESCRIPTION
**Pull request by hughperkins**
I dont think is quite ready for merge just yet, since the model files are 1.6GB each, but it does run at least :-)  Albeit slowly :-D

### CODE REVIEW

**Comment by hughperkins** [comment]
(Well... since it's always the same 1.6GB model file, and it's once every 50 epochs, maybe it's kind of usable???)

**Comment by szagoruyko** [comment]
hi Hugh, thanks, same as https://github.com/szagoruyko/cifar.torch/pull/15 I forgot to merge it. what's the problem with clearState in clnn?

**Comment by hughperkins** [comment]
> what's the problem with clearState in clnn?

Not sure.  But if you run it, then do the save, then carry on training, it eats ~2GB gpu memory per save :-P

**Comment by hughperkins** [comment]
>  thanks, same as #15 

Ah yes, your solution is nice and clean :-)

**Comment by hughperkins** [comment]
(seems I can reproduce the opencl clearstate issue using:

```
require 'clnn'

local model = nn.Sequential()
model:add(nn.Linear(4096,128))
model:cl()

local inputs = torch.ClTensor(128, 4096)

for i=1,250 do
  print('i', i)
  local out = model:forward(inputs)
  model:backward(inputs, out)
  model:clearState()
  torch.save('/tmp/foo.dat', model)
end
```

... and monitoring using eg:

```
while true; do { nvidia-smi ; sleep 0.1; } done
```

)

**Comment by fmassa** [comment]
@hughperkins I think I found the reason for the memory leak. I just opened an issue in `cltorch`

**Comment by hughperkins** [comment]
Hi Sergey, following Francisco's fix, clearstate works very well now on opencl version :-)

**Comment by szagoruyko** [comment]
cool thanks @hughperkins @fmassa

**Comment by hughperkins** [comment]
By the way, if you update to very latest version of cltorch/clnn, it's about ~25% faster now (tested on K520), after adding batched SGEMM, per Junli Gu's paper http://www.iwocl.org/attend/sessions/  I've only added on forward pass for now.  I imagine if I add also for backprop, there will be similar gains plausibly.  Basically on K520, I was getting ~17.5 minutes per epoch before, and ~13 minute per epoch now.

**Comment by hughperkins** [comment]
(Just for info, I moved OpenCL torch to run off Torch as it was around ~21 February, https://github.com/hughperkins/distro .  I've cherry-picked some of the changes since then.  And it continues to run cifar.torch ok :-)  (though it temporarily didnt :-D  for about ~6 hours)

**Pull request closed without merging**
